### ISSUE TITLE
Something wrong in IHC8342B sensor.

### ISSUE THREAD

**Issue by jyz0501** [Zrincet/IHC8342B_query#3]
Logger: custom_components.IHC8342B_query.sensor
Source: custom_components/IHC8342B_query/sensor.py:172 
Integration: IHC8342B_query ([documentation](https://github.com/zrincet/IHC8342B_query)) 
First occurred: 00:23:17 (3 occurrences) 
Last logged: 00:33:23

Something wrong in IHC8342B sensor.
Traceback (most recent call last):
  File "/config/custom_components/IHC8342B_query/sensor.py", line 172, in update
    startEle = float(re_json['table'][0]['values'][0]['elec']) / 100
TypeError: 'NoneType' object is not subscriptable

**Comment by Zrincet** [comment]
我这边测试好像没出现这个问题，你可以试试现在还有没有这个问题？
